# ===================================================
# meta infos
# ===================================================

meta:
  project: techpoc
  include:
    - dobi.yaml
    - version.yaml
    - torizon-builder/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - techpoc-version
  annotations:
    description: "[alias] techpoc-version"

alias=build:
  tasks:
    - techpoc-build
  annotations:
    description: "[alias] techpoc-build"

alias=deploy:
  tasks:
    - techpoc-deploy
  annotations:
    description: "[alias] techpoc-deploy"

alias=test:
  tasks:
    - techpoc-test
  annotations:
    description: "[alias] techpoc-test"
