---
# Project configuration
# -----------------------------
## Defines the name for the project
name: techpoc
## Specify the namespace for the building block image. This gets prefixed before <prefix>/<name>
### example: docker_namespace: "harbor/ci4rail" results in using "harbor/ci4rail/<name>"
### "ci4rail" means using the docker hub, e.b. "ci4rail/<name>"
docker_registry: "harbor.lan:8080"

docker_namespace: "ci4rail"
## Specifies insecure docker registries, format "host:port" or "ip:port", leave empty if unused, e.g. ""
destination_insecure_registry: "harbor.lan:8080"
## Specify if 'latest' tags are built for `git_branch`
release_as_latest: true

# Git configuration
# -----------------
## Specify the git repository to work with
git_source: https://github.com/ci4rail/techpoc.git
## Specify the git branch to work with
git_branch: master
## This enables/disables ssl verification of the git resource
git_skip_ssl_verification: false

# S3 configuration
# ----------------
## Specify the S3 endpoint URI
s3_endpoint: http://minio:9000
## This enables/disables the ssl verification for the S3 endpoint
s3_skip_ssl_verification: true
